name: "Build"
on: [push, workflow_dispatch]
jobs:
  uberjar:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup Java"
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: "Setup Clojure"
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: "1.10.1.697"
      - name: "Clojure Tests"
        run: clojure -A:dev:test
      - name: "Uberjar"
        run: clojure -A:uberjar
      - name: "Upload"
        uses: actions/upload-artifact@v2
        with:
          name: dj-data-converter-standalone
          path: target/dj-data-converter-SNAPSHOT-standalone.jar
  native-image-linux:
    needs: [uberjar]
    runs-on: ubuntu-latest
    steps:
      - name: "Setup GraalVM"
        uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: "20.2.0.java11"
      - name: "Install GraalVM Native Image Deps"
        run: |
          sudo apt -y update
          sudo apt -y install gcc libc6-dev zlib1g-dev libstdc++-8-dev
      - name: "Install GraalVM Native Image"
        run: gu install native-image
      - name: "Download"
        uses: actions/download-artifact@v2
        with:
          name: dj-data-converter-standalone
      - name: "Native Image"
        run: native-image --verbose --no-server --no-fallback --allow-incomplete-classpath --report-unsupported-elements-at-runtime --initialize-at-build-time -J-Xmx8g -jar dj-data-converter-SNAPSHOT-standalone.jar -H:Name=dj-data-converter
      - name: "Smoke Test"
        run: |
          chmod +x dj-data-converter
          ./dj-data-converter -h
      - name: "Package"
        run: tar -czvf dj-data-converter-linux.tar.gz dj-data-converter
      - name: "Publish"
        uses: actions/upload-artifact@v2
        with:
          name: 'dj-data-converter-linux'
          path: dj-data-converter-linux.tar.gz
  native-image-windows:
    needs: [uberjar]
    runs-on: windows-latest
    steps:
      - name: "Setup GraalVM"
        uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: "20.2.0.java11"
      - name: "Install GraalVM Native Image"
        run: C:\hostedtoolcache\windows\GraalVM\20.2.0-java11\x64\bin\gu install native-image
      - name: "Download"
        uses: actions/download-artifact@v2
        with:
          name: dj-data-converter-standalone
      - name: "Native Image"
        run: native-image --verbose --no-server --no-fallback --allow-incomplete-classpath --report-unsupported-elements-at-runtime --initialize-at-build-time -J-Xmx8g -jar dj-data-converter-SNAPSHOT-standalone.jar -H:Name=dj-data-converter
      - name: "Smoke Test"
        run: dj-data-converter.exe -h